Update 01-getting-started.md
Update getting started guide to use <?pp instead of <?php.

This eliminates the following error following these instructions:
Fatal error: HHVM 4+ does not support PHP: <filename>