Pin to last 1.X composer version (currently 1.0.24)
Composer 2.2.1 was erroring with:

  Fatal error: The dollar sign `$` cannot be used as a unary operator in /var/www/vendor/bin/hh-autoload.hack on line 3

This was because hh-autoload.hack is a bash script that wraps the main
hh-autoload.hack. It's not clear if this is an issue our side or
upstream.